ENH: added two new options to control OpenCL device execution for elastix and transformix.
  1. Option (OpenCLDeviceType "GPU") or (OpenCLDeviceType "CPU")
    Controls the OpenCL device type. Currently only CPU, GPU devices are supported. 
    If you have other accelerators avaliable, add support for it, test it and send us the patch.
    
     - For NVIDIA graphical cards (OpenCLDeviceType "GPU") option, download OpenCL drivers from:
       http://www.nvidia.com/Download/index.aspx
     - For AMD processors (OpenCLDeviceType "CPU") option or graphical cards (OpenCLDeviceType "GPU") option, download OpenCL drivers from:
       http://support.amd.com/en-us/download
     - For Intel processors (OpenCLDeviceType "CPU") option or "HD graphical cards (OpenCLDeviceType "GPU") option, download OpenCL drivers from:
       https://software.intel.com/en-us/intel-opencl/download
       
       Note: Intel HD GPU's only supports float for computations, elastix will not run in OpenCL mode for them.
             We are planning to investigate whether this strict check still applicable.
       
  2. Option (OpenCLDeviceID "") allows selecting the OpenCL device ID. See examples in section 4.

    Here is the wrong way of selecting the device that does not exist on the system with (OpenCLDeviceID "3") and elastix response:
    ERROR: You have selected the OpenCL device ID: 3, with (OpenCLDeviceID "3") option.
      There are only 2 GPU OpenCL-enabled devices present on this system:
      OpenCL device ID: 0
        Name: GeForce GTX 980 Ti
        Vendor: NVIDIA Corporation
        Has double support: Yes
        Device type: GPU
      elastix option: (OpenCLDeviceID "0")
      OpenCL device ID: 1
        Name: NVS 310
        Vendor: NVIDIA Corporation
        Has double support: Yes
        Device type: GPU
      elastix option: (OpenCLDeviceID "1")
    
    Providing correct OpenCL device ID with (OpenCLDeviceID "0") or (OpenCLDeviceID "1") allows switching between the graphical cards.
    
  3. If none of this OpenCLDeviceType or OpenCLDeviceID options are provided, then single maximum flops device is used.
     That was default behaviour and it is going to be the same. The maximum flops device computed using following formula:
     int device_flops = ( *device ).GetComputeUnits() * ( *device ).GetClockFrequency()
     This is naive approach of computing the most powerful device. In real live it is more complex.
     But, this simple way works fine in the most situations. Although, you could select something else in future.

  4 Examples:
    4.1 Selecting GeForce GTX 980 Ti in parameters file:
      // OpenCL specific
      (OpenCLDeviceType "GPU")
      (OpenCLDeviceID "0")
    4.2 Selecting GeForce NVS 310 in parameters file:4
      // OpenCL specific
      (OpenCLDeviceType "GPU")
      (OpenCLDeviceID "1")
    4.3 Selecting Intel(R) Xeon(R) CPU in parameters file:
      // OpenCL specific
      (OpenCLDeviceType "CPU")
      (OpenCLDeviceID "0")
      
      Note: OpenCL™ Runtime for Intel® Core™ and Intel® Xeon® Processors for Windows*(64-bit & 32-bit)
            has to be installed on the system.
            https://software.intel.com/en-us/articles/opencl-drivers

      Note: On the Ubuntu or other Linux distributions Intel’s OpenCL library could be already installed by default.
            Check for /usr/lib/libOpenCL.so or something similar.
     
   5. Questions/Answers:
    Question: I have error OpenCL.dll is not present on my system. What should I do?
    Answer: Install the graphical drivers for your system! OMG, you are doing image processing!? 8)
    
    Question: Will I get performance with Intel OpenCL runtime on CPU over normal elastix CPU execution?
    Answer: Yes, depending on setup around 4-5x during resampling.
            I don't have exact numbers in my hand, but back into 2013 the following execution on Intel Xeon OpenCL results in following timings:
              Interpolator : BSpline order 3
              Transform : CompositeTransform [TranslationTransform, AffineTransform, BSplineTransform, Euler3DTransform, Similarity3DTransform]
              Image size: 512x512x256
              CPU: 57.3482sec
              Intel OpenCL on CPU 13.6209sec
              Speed up: 4.2103
              RMS Error: 0.041727
              
   Have fun ;)
   Denis P. Shamonin


git-svn-id: https://svn.bigr.nl/elastix/trunkpublic@5265 4d348492-3962-11de-aa85-65a2020054a3